### ISSUE TITLE
lauxlib.h: no such file or directory

### ISSUE THREAD

**Issue by nargyriou** [ers35/luastatic#18]
Solved.

Dear google person: 

If you don't find lauxlib.h, find it with

`locate lauxlib.h`

Then as per the readme says

`luastatic main.lua` `/usr/lib/x86_64-linux-gnu/liblua5.2.a` `-I<lauxlib.h parent folder>`

**Comment by Barmaley0** [comment]
Hello. Can you tell me what to do in this case?
![Screenshot 2024-04-25 192348](https://github.com/ers35/luastatic/assets/133758633/2f8d7e2c-5392-4b8b-8084-3a911ab57499)

**Comment by ers35** [comment]
Is the file `lauxlib.h` in the `/deps/lua51_include` directory? It might be in a subdirectory like `lua/lauxlib.h`. In that case, you'd add another `-I/deps/lua51_include/lua` to the compiler arguments.

**Comment by Barmaley0** [comment]
Eric thank you, I found a solution)

**Comment by nargyriou** [comment]
> Eric thank you, I found a solution)

Please detail your solution for the people coming from Google later on
