### ISSUE TITLE
luastatic not including libraries in subdirectories

### ISSUE THREAD

**Issue by daveyc** [ers35/luastatic#2]
I tried to build a static binary using the following command.

luastatic hw.lua pl/pretty.lua pl/utils.lua pl/compat.lua pl/lexer.lua socket/core.a /usr/local/lib/liblua.a -I/u/lua/static/lua-5.1.5/src

The socket/core.a library was not included. I had a quick look at the code and it seems this is because luastatic uses "basename" to strip of the directory name. 

This looks like a promising tool but IMO would be better with proper command line parsing. I want to include code that's installed in /usr/local/*/lua/* directories but found that I have to create symlinks to do so. Command options like -p /usr/local/share/lua/5.n and -L /usr/local/lib/lua/5.n would make it more usable.

**Comment by ers35** [comment]
I reproduced the issue of a library like socket/core.a not being included and I am working on a fix.

One of the design goals of luastatic is to attempt to detect what to do with the files specified on the command line without the need of flags. I will try to resolve your issue without adding flags.

I'll see what I can do about including code from an absolute directory like /usr/local/lua.
