### ISSUE TITLE
luastatic destroys source file in some configurations

### ISSUE THREAD

**Issue by mp035** [ers35/luastatic#23]
Hi, 
Great work on luastatic, it works very well.  I have a problem with my project which has the source file with the main entry point named ir2net.lua, and the project directory named ir2net.

During compilation luastatic overwrites the main script (ir2net.lua) with what appears to be an intermediate elf file.

This behavior destroys my main source file and I loose all work since my last git commit.  luastatic should check if a source file exists before overwriting it, or at the very least there should be a warning in the readme to alert users that they could loose their work in this configuration.

**Comment by ers35** [comment]
luastatic only creates one intermediate file named ir2net.lua.c and runs the compiler to create a binary executable named ir2net.

What command are you using to run luastatic? If you're using a Makefile, please post the Makefile rule.

**Comment by mp035** [comment]
WOW! that was fast!.
Yes, I am using a makefile.  The data that it overwrites the file with is partly binary, and looks like an ELF file. Here is the makefile rule:
```
ir2net: luars232.a luaselect.a bit.a main.lua console_packet_server.lua JSON.lua slugify.lua intelhex.lua irpacket.lua packet_server.lua resource_controllers.lua
	luastatic ir2net.lua console_packet_server.lua JSON.lua slugify.lua intelhex.lua irpacket.lua \
	    packet_server.lua resource_controllers.lua /usr/lib/x86_64-linux-gnu/liblua5.1.a luars232.a  \
	    bit.a luaselect.a -I/usr/include/lua5.1/
```
Could it be the C compiler compiling ir2net.lua.c -> ir2net.lua ?

**Comment by mp035** [comment]
Ok, so it gets weirder.  I can reproduce the issue, but it only happens every second time I run make.  The first time the source file is untouched, the second time, it is overwritten.  If I restore the source file from a backup, the behaviour repeats.

**Comment by ers35** [comment]
The problem is a Makefile implicit rule that tries to compile ir2net.lua.c to ir2net.lua. Make is doing this, not luastatic.

Cancel the implicit rule by modifying the Makefile like this:
```
%.lua:

ir2net: ir2net.lua
	luastatic ir2net.lua /usr/lib/x86_64-linux-gnu/liblua5.1.a -I/usr/include/lua5.1/
```

See also: https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_10.html#SEC104

**Comment by mp035** [comment]
You sir are an absolute legend!  Thank you so much.  I would have never found that.

**Comment by mp035** [comment]
Just a thought.  How difficult would it be to have luastatic rename the intermediate file, in my case to use a name like ir2net.luastatic.c (by adding 'static.c' instead of just '.c').

This would completely prevent this problem.  I would think that this is not an uncommon situation.

**Comment by ers35** [comment]
It's a good idea. I'll look into it.
