### ISSUE TITLE
Invoke requireF for C modules

### ISSUE THREAD

**Issue by turbo** [ers35/luastatic#25]
I use luastatic with openresty/LuaJIT2 and static compilation. One thing I'd like to see is the automatic loading of supplied C modules during the initial state construction.

For example, I want to include int64 support, which is povided by PUC's `lint64.c` module. I have monkeypatched luastatic like this (following added to template `out`):

```c
void luaL_requiref (lua_State *L, char const* modname,
                    lua_CFunction openf) {
  luaL_checkstack(L, 3, "not enough stack slots");
  lua_pushcfunction(L, openf);
  lua_pushstring(L, modname);
  lua_call(L, 1, 1);
  lua_getglobal(L, "package");
  lua_getfield(L, -1, "loaded");
  lua_replace(L, -2);
  lua_pushvalue(L, -2);
  lua_setfield(L, -2, modname);
  lua_pop(L, 1);
}

int luaopen_int64(lua_State *L);

int main(int argc, char *argv[])
{
  lua_State *L = luaL_newstate();
  luaL_openlibs(L);
  createargtable(L, argv, argc, 0);
  luaL_requiref(L, "int64", luaopen_int64);
```

(the `luaL_requiref` polyfill comes from Kepler's compat-5.2 C API, one may wish to exclude that for Lua > 5.1)

I then invoke luastatic like this:

```bash
luastatic con.lua lint64-101/lint64.c src/libluajit.a -I./src/ -I./lint64-101 -static
```

This all works because `lint64-101/lint64.c` is passed as a compiler argument. My request is that luastatic parses `.c` files in it's arguments and emits the `luaL_requiref` calls automatically. The user would still need to supply include dirs used by the C module, but this simplifies static compilations.

**Comment by ers35** [comment]
What do you think about building lint64.c to an object file before passing it to luastatic?

Example:

```
-- main.lua
print(require("module"))
```

```
// module.c
#include <lua.h>

int luaopen_module(lua_State *l)
{
    lua_pushstring(l, "hello");
    return 1;
}

```

`CFLAGS="-I/usr/include/lua5.3" make module.o && luastatic main.lua module.o -llua5.3 -I/usr/include/lua5.3`
