### ISSUE TITLE
Refuses to build unless the entry point ends in .lua

### ISSUE THREAD

**Issue by technomancy** [ers35/luastatic#27]
I've got a Lua script which doesn't end in `.lua`, but when I try to use `luastatic` on it, it refuses to build:

    $ luastatic fennel /usr/lib/x86_64-linux-gnu/libluajit-5.1.a -I /usr/include/luajit-2.0
    luastatic 0.0.9
    usage: luastatic main.lua[1] require.lua[2] liblua.a[3] library.a[4] -I/include/lua[5] [6]
      [1]: The entry point to the Lua program
      [2]: One or more required Lua source files
      [3]: The path to the Lua interpreter static library
      [4]: One or more static libraries for a required Lua binary module
      [5]: The path to the directory containing lua.h
      [6]: Additional arguments are passed to the C compiler

If I rename the file, it will run, but that conflicts with other files I have in my repo. It would be nice to be able to specify an output file and accept an input which does not end in `.lua`.

I could prepare a patch to do this if you agree it's a good idea.

**Comment by ers35** [comment]
One workaround is to rename `fennel` to `fennel.luac`. `.luac` is meant for bytecode but `luastatic` does not treat it any differently. You can use `-o` passed to the compiler to control the output filename:
`luastatic fennel.luac /usr/lib/x86_64-linux-gnu/liblua5.3.a -I/usr/include/lua5.3 -o fennel.out`

**Comment by technomancy** [comment]
Hm; that would work, but that is not the name I would like to use for the file in question. Is it difficult to make it accept files with no extension?

Another workaround would be to make it accept input on stdin when the first arg is `-`, which is how most unix tools work; then the filename is irrelevant.

**Comment by ers35** [comment]
`luastatic` is a bit strange in that it accepts arguments in any order and doesn't parse `getopt` style arguments. Any unrecognized arguments are passed to the C compiler.

This patch makes it accept files with no extension as the first argument:
```patch
diff --git a/luastatic.lua b/luastatic.lua
index 06a7564..6a04d3b 100755
--- a/luastatic.lua
+++ b/luastatic.lua
@@ -99,9 +99,9 @@ passed to the compiler in the order they appear and may be interspersed with arg
 the compiler. Arguments to the compiler are passed to the compiler in the order they 
 appear.
 --]]
-for _, name in ipairs(arg) do
+for i, name in ipairs(arg) do
        local extension = name:match("%.(%a+)$")
-       if is_source_file(extension) or is_binary_library(extension) then
+       if i == 1 or (is_source_file(extension) or is_binary_library(extension)) then
                if not file_exists(name) then
                        io.stderr:write("file does not exist: " .. name .. "\n")
                        os.exit(1)
@@ -110,17 +110,17 @@ for _, name in ipairs(arg) do
                local info = {}
                info.path = name
                info.basename = basename(info.path)
-               info.basename_noextension = info.basename:match("(.+)%.")
+               info.basename_noextension = info.basename:match("(.+)%.") or info.basename
                --[[
                Handle the common case of "./path/to/file.lua".
                This won't work in all cases.
                --]]
                info.dotpath = info.path:gsub("^%.%/", "")
                info.dotpath = info.dotpath:gsub("[\\/]", ".")
-               info.dotpath_noextension = info.dotpath:match("(.+)%.")
+               info.dotpath_noextension = info.dotpath:match("(.+)%.") or info.dotpath
                info.dotpath_underscore = info.dotpath_noextension:gsub("[.-]", "_")
 
-               if is_source_file(extension) then
+               if i == 1 or is_source_file(extension) then
                        table.insert(lua_source_files, info)
                elseif is_binary_library(extension) then
                        -- The library is either a Lua module or a library dependency.
```

**Comment by technomancy** [comment]
That looks perfect; thanks. I tried it out and it does the job. It seems to make the behavior follow the suggestions in the readme more closely IMO. Will you apply the patch?
