### ISSUE TITLE
Including all the modules from other directories

### ISSUE THREAD

**Issue by aniruddha-a** [ers35/luastatic#28]
Hello,

In my main Lua module, I use some thirdparty modules kept in a separate directory like

`local argp    = require 'thirdparty/argparse'`
`local colors  = require 'thirdparty/ansicolors'`

While building my exe with Luastatic, I am passing these also as arguments and I get the
required exe, but when I run the exe from another directory (than were the code resides), I get the following err:

`[string "yang"]:2: module 'thirdparty/argparse' not found:`
`	no field package.preload['thirdparty/argparse']`
`	no module 'thirdparty/argparse' in luastatic bundle`

Is this something to do with the way I used `require` or something wrong with the
way I am passing the modules to `luastatic` ?
This is my command:

`luastatic.lua main.lua thirdparty/argparse.lua ... -I $LUAJIT_INC_DIR  -L $LUAJIT_LIB_DIR -lluajit -lm -ldl`

Is this OK ? or do I have to first compile the modules to `.a` and then link ?

Thanks

--
Ani

**Comment by ers35** [comment]
Try with [0.0.12](https://luarocks.org/modules/ers35/luastatic/0.0.12-1).

**Comment by aniruddha-a** [comment]
Thanks Eric, that worked.
