### ISSUE TITLE
FFI can't access C functions after static linking

### ISSUE THREAD

**Issue by turbo** [ers35/luastatic#29]
HI,

I have a Lua(-only) project that I'm trying to compile with luastatic. Here's the command it generates:

```bash
cc -Os scratch.luastatic.c ./vendor/luajit2/dbin/lib/libluajit-5.1.a -rdynamic -lm -ldl -o scratch2 -I./vendor
/luajit2/dbin/include/luajit-2.1/ -static
```

I only added `-static` and provided paths to a static build of LuaJIT.

This succeeds in building a static binary, however when I run it, I get this error:

```text
[string "moot.signal"]:5: Symbol not found: signal
stack traceback:
	[C]: in function '__index'
	[string "moot.signal"]:5: in main chunk
```

Which traces back to a simple `foo = ffi.C.signal` in the `moot.signal` module. It seems like either the signal symbols aren't being linked or LuaJIT/FFI can't access them.

If I compile it without `-static`, it works.

**Comment by turbo** [comment]
Here's the simplest example:

main.lua

```lua
local ffi = require "ffi"
local signal = ffi.C.signal
```

this will throw:

```text
[string "main"]:2: missing declaration for symbol 'signal'
stack traceback:
	[C]: in function '__index'
	[string "main"]:2: in function 'func'
	[string "main"]:39: in main chunk
```

On both static and dynamic compile. When the symbol is declared like 


```lua
local ffi = require "ffi"

ffi.cdef([[
  typedef void(*sighandler_t)(int);
  sighandler_t signal(int signum, sighandler_t handler);
]])

local signal = ffi.C.signal
```

Then only the statically compiled binary fails with:

```text
[string "main"]:8: main: undefined symbol: signal
stack traceback:
	[C]: in function '__index'
	[string "main"]:8: in function 'func'
	[string "main"]:39: in main chunk
```

**Comment by ers35** [comment]
The LuaJIT FFI uses `dlsym` to load symbols. `dlsym` won't find symbols in a statically linked binary.
See also:
https://www.freelists.org/post/luajit/How-to-call-functions-from-a-static-library-in-Luajit,8
https://www.openwall.com/lists/musl/2012/12/08/4

Why do you need to use `-static` in this case? Can you statically link everything else and dynamically link with libc?

**Comment by turbo** [comment]
> Why do you need to use -static in this case?

Because I want to produce a static binary for easier distribution. libc is also the only dependency in the actual project. The only alternative would be something like Ermine, but that's quite pricey.

**Comment by ers35** [comment]
If you can modify the `moot` library, try the advice from the LuaJIT author linked above.

**Comment by turbo** [comment]
At hundreds of symbols pulled in via FFI, this would be a huge task but seems to be the only way. I'll take a look, thx.

**Comment by turbo** [comment]
@ers35 I'm not quite sure I completely understand Pall's way of declaring that struct. Does the following sound right?

In the luastatic generated C file, I'd add:

```c
// somewhere up top
struct t_myfuncs {
    sighandler_t (*signal)(int signum, sighandler_t handler);
};

static struct t_myfuncs myfuncs;

myfuncs.signal = signal

struct t_myfuncs *p_myfuncs = &myfuncs;

// is this right? if so, where should it appear?
lua_pushlightuserdata(L, p_myfuncs);
lua_setglobal(L, "myfuncs");
```

and then in Lua-land:

```moonscript
ffi.cdef [[
  struct t_myfuncs {
    sighandler_t (*signal)(int signum, sighandler_t handler);
  };
]]

myfuncs = ffi.cast("struct t_myfuncs *", myfuncs)
-- proceed to use myfuncs.signal(...) somewhere
```

**Comment by turbo** [comment]
This seemed to work, though further testing is in progress:

###### Lua

```moonscript
unless _G.calltable
  print(Inspect(:myfuncs))

  -- typedef void(*sighandler_t)(int);
  FFI.cdef [[
    struct t_myfuncs {
      sighandler_t (*signal)(int signum, sighandler_t handler);
    };
  ]]

  lua_myfuncs = FFI.cast("struct t_myfuncs *", myfuncs)

  print(Inspect(:lua_myfuncs))

  with lua_myfuncs
    _G.calltable = {
      signal: (a, b) ->
        print "signal called"
        .signal(a, b)
    }
```

###### In C stream, after includes

```c
typedef void(*sighandler_t)(int);
struct t_myfuncs {
  sighandler_t (*signal)(int signum, sighandler_t handler);
};
```

###### In C stream, before `docall`

```c
static struct t_myfuncs myfuncs;
myfuncs.signal = signal;
lua_pushlightuserdata(L, &myfuncs);
lua_setglobal(L, "myfuncs");
```

**Comment by ers35** [comment]
I suggest making a separate Lua module rather than modifying the generated C file:
```c
// funcs.c
#include <lua.h>
#include <stdio.h>

struct funcs
{
	int (*puts)(const char *s);
};

static struct funcs funcs = 
{
	.puts = puts,
};

int luaopen_funcs(lua_State *l)
{
	lua_pushlightuserdata(l, &funcs);
	return 1;
}

```

```lua
-- cc -c funcs.c -I/usr/include/luajit-2.1
-- luastatic main.lua funcs.o -lluajit-5.1 -I/usr/include/luajit-2.1
local ffi = require("ffi")
local funcs = require("funcs")

ffi.cdef([[
struct funcs
{
	int (*puts)(const char *s);
};
]]
)

funcsffi = ffi.cast("struct funcs*", funcs)
funcsffi.puts("hello")

```

**Comment by turbo** [comment]
Very good idea. Thanks.

**Comment by turbo** [comment]
Here's another trick that might save time on the Lua end:

```c
#define CONS_CALLTABLE(members) \
  static const char _calltable_decl[] = #members; \
  struct calltable { members };

CONS_CALLTABLE(
  sighandler_t (*signal)(int signum, sighandler_t handler);
  // ...
)
```

Now `_calltable_decl` can be pushed as a string to Lua and passed to `cdef` without duplicating the code.

**Comment by turbo** [comment]
Yay, it worked! Now it builds statically. To disable dynamic loading, I had to override the default for `LJ_TARGET_DLOPEN` for my arch. So I compile LuaJIT with:

```bash
make -j \
  STATIC_CC="/usr/local/musl/bin/musl-gcc" \
  CCOPT="-static -fPIC -DLJ_TARGET_DLOPEN=0" \
  BUILDMODE="static" \
  PREFIX="$(pwd)/dbin"
```

and add a small patch to `lj_arch.h`:

```c
// #define LJ_TARGET_DLOPEN    LJ_TARGET_POSIX
```

I don't know if there's an easier way, but this eliminates the need for `-ldl` and thus makes it independent from glibc version.
