### ISSUE TITLE
Support for LuaJIT Objects

### ISSUE THREAD

**Issue by turbo** [ers35/luastatic#30]
Hi,

Is it possible to supply LuaJIT object files to luastatic instead of scripts? I don't necessarily want my Lua script to appear as a string in the final binary. I ran a quick test by just adding the object file to the luastatic command but the main script failed to load the linked module - though it's likely I messed up the luastatic invokation.

Thanks!

**Comment by ers35** [comment]
This worked for me:
```
luajit -b bytecode.lua bytecode.luac
luastatic bytecode.luac /usr/lib/x86_64-linux-gnu/libluajit-5.1.a -I/usr/include/luajit-2.1/
```

**Comment by turbo** [comment]
That worked, thanks.
