### ISSUE TITLE
Disable External Lua Module Loading

### ISSUE THREAD

**Issue by turbo** [ers35/luastatic#31]
(I promise, that's the last one for today)

A cursory `strace` (or a package loading error) reveals the final binary is still looking on disk for modules if it doesn't find them in the bundle. How can I disable all external module loading? In a way that a CPATH env variable can't re-enable it?

Thanks

**Comment by ers35** [comment]
Lua uses the [package.searchers](https://www.lua.org/manual/5.3/manual.html#pdf-package.searchers) table to decide how to load modules. `luastatic` adds its own searcher function to find modules in the bundle. One way to lock this down is to remove searchers you do not want early in your program:
```lua
table.remove(package.searchers)
table.remove(package.searchers)
table.remove(package.searchers)
require("module")
```

```
module 'module' not found:
	no field package.preload['module']
	no module 'module' in luastatic bundle
```

**Comment by turbo** [comment]
Is that Lua 5.3 exclusive? I'm getting a 

```text
[string "scratch"]:1: bad argument #1 to 'remove' (table expected, got nil)
stack traceback:
	[builtin:remove]: in function 'remove'
	[string "scratch"]:1: in function 'func'
	[string "scratch"]:39: in main chunk
```

for Lua 5.1 (LJ)

**Comment by turbo** [comment]
Yep, in 5.1 it's:

```lua
table.remove(package.loaders)
table.remove(package.loaders)
table.remove(package.loaders)
```

which is working :)
