### ISSUE TITLE
Should binary be stipped by default?

### ISSUE THREAD

**Issue by mosolovsa** [ers35/luastatic#37]
Looks like compiler receives argument -s which means optimize size.
Maybe we should strip resulting executable by default also?

 serg@mosolov  ~/projects/test/luafltk/win  CC=/home/serg/crscmpl/mxe/usr/bin/i686-w64-mingw32.static-g++ luastatic main.lua libmoonfltk.a /home/serg/crscmpl/mxe/usr/i686-w64-mingw32.static/lib/liblua.a -I/home/serg/crscmpl/mxe/usr/i686-w64-mingw32.static/include /home/serg/crscmpl/mxe/usr/i686-w64-mingw32.static/lib/libfltk.a -lgdi32 -lole32 -lcomctl32 -luuid -lws2_32 -lcomdlg32 -mwindows
/home/serg/crscmpl/mxe/usr/bin/i686-w64-mingw32.static-g++ -Os main.luastatic.c libmoonfltk.a /home/serg/crscmpl/mxe/usr/i686-w64-mingw32.static/lib/liblua.a /home/serg/crscmpl/mxe/usr/i686-w64-mingw32.static/lib/libfltk.a  -lm  -o main.exe -I/home/serg/crscmpl/mxe/usr/i686-w64-mingw32.static/include -lgdi32 -lole32 -lcomctl32 -luuid -lws2_32 -lcomdlg32 -mwindows
 serg@mosolov  ~/projects/test/luafltk/win  ls -l                                                                                                                      ✔  6879  10:42:15
total 3760
-rwxrwxr-x 1 serg serg     556 мар 24 15:14 crscmpl
-rw-rw-r-- 1 serg serg  850450 мар 24 13:47 libmoonfltk.a
-rw-rw-r-- 1 serg serg    1852 мар 24 14:55 main.cpp
-rwxrwxr-x 1 serg serg 2644259 апр 23 10:42 main.exe
-rw-rw-r-- 1 serg serg    1275 апр 23 09:18 main.lua
-rw-rw-r-- 1 serg serg   17394 апр 23 10:42 main.luastatic.c
-rw-rw-r-- 1 serg serg   17394 апр 23 10:11 main.luastatic.c_after
-rw-rw-r-- 1 serg serg   17472 апр 23 10:11 main.luastatic.c_fixed
-rw-rw-r-- 1 serg serg  278148 апр 23 09:23 out.txt
 serg@mosolov  ~/projects/test/luafltk/win  ~/crscmpl/mxe/usr/bin/i686-w64-mingw32.static-strip main.exe                                                               ✔  6880  10:42:16
 serg@mosolov  ~/projects/test/luafltk/win  ls                                                                                                                         ✔  6881  10:42:30
crscmpl  libmoonfltk.a  main.cpp  main.exe  main.lua  main.luastatic.c  main.luastatic.c_after  main.luastatic.c_fixed  out.txt
 serg@mosolov  ~/projects/test/luafltk/win  ls -l                                                                                                                      ✔  6882  10:42:30
total 2700
-rwxrwxr-x 1 serg serg     556 мар 24 15:14 crscmpl
-rw-rw-r-- 1 serg serg  850450 мар 24 13:47 libmoonfltk.a
-rw-rw-r-- 1 serg serg    1852 мар 24 14:55 main.cpp
-rwxrwxr-x 1 serg serg 1557504 апр 23 10:42 main.exe
-rw-rw-r-- 1 serg serg    1275 апр 23 09:18 main.lua
-rw-rw-r-- 1 serg serg   17394 апр 23 10:42 main.luastatic.c
-rw-rw-r-- 1 serg serg   17394 апр 23 10:11 main.luastatic.c_after
-rw-rw-r-- 1 serg serg   17472 апр 23 10:11 main.luastatic.c_fixed
-rw-rw-r-- 1 serg serg  278148 апр 23 09:23 out.txt

before strip:
-rwxrwxr-x 1 serg serg 2644259 апр 23 10:42 main.exe
after strip:
-rwxrwxr-x 1 serg serg 1557504 апр 23 10:42 main.exe

**Comment by ers35** [comment]
The `-Os` only applies to files compiled alongside `luastatic`, typically only main.luastatic.c. Stripping applies to the whole binary including any .o or .a files linked. I prefer to leave that option up to the user.
