### ISSUE TITLE
Improvement to documentation 

### ISSUE THREAD

**Issue by mystery-z** [ers35/luastatic#41]
As a newcomer to lua, I found this documentation much better than other lua-related projects' documentation. 

Also, it's my first time submitting an issue to an open-source project, so please tell me if this sounds a bit over-the-top.

Anyways, I think we should add the following for people who installed lua through homebrew:

`/opt/homebrew/Cellar/lua/5.4.4_1/include/lua/lauxlib.h` =  whenever laxulib.h is needed

`/opt/homebrew/Cellar/lua/5.4.4_1/lib/liblua.a - liblua.a` = whenever liblua is needed

`/opt/homebrew/Cellar/lua/5.4.4_1/include/lua/` = directory to folder containing lua.h 

`Luastatic main.lua /opt/homebrew/Cellar/lua/5.4.4_1/lib/liblua.a -I/opt/homebrew/Cellar/lua/5.4.4_1/include/lua/ `- complete lua compiler script for "main.lua"

Normally, directory paths aren't that hard to get, but they don't appear on any homebrew documentation and hence I had to dig deep to find where homebrew had put these files. 

I just think this will make luastatic more convenient to use if we add this documentation. Thanks for reading.

**Comment by mystery-z** [comment]
@ers35 So can we have this added to the bottom of the Readme file?

**Comment by ers35** [comment]
I added instructions for Homebrew: https://github.com/ers35/luastatic#lua-using-homebrew

**Comment by mystery-z** [comment]
Nice! Thanks for the quick response~
