### ISSUE TITLE
module 'basetool' not found

### ISSUE THREAD

**Issue by oneStarCai** [ers35/luastatic#44]
I user 0.0.12, It works normally when running in the current directory, but runs abnormally when copied to other directories.
![image](https://github.com/ers35/luastatic/assets/4077572/79d4e9b8-0ef5-44b8-bbab-5af88068367d)
![image](https://github.com/ers35/luastatic/assets/4077572/31fdfa0e-41c3-4a1c-a364-8718bb1948db)
How to solve it ?

**Comment by ers35** [comment]
In main.lua, are you calling `require("basetool")` or `require("logic.basetool")`?

If you want to `require("basetool")`, copy basetool.lua to the same directory as main.lua. Otherwise, change your code to `require("logic.basetool")`.

**Comment by oneStarCai** [comment]
yes, I fix it. it's  that "package.path" shouldn't be set.
