### ISSUE TITLE
Static linking option in luastatic.lua

### ISSUE THREAD

**Issue by yuhangwang** [ers35/luastatic#7]
It seems like the current luastatic.lua only does dynamic linking:
```
cc -Os -std=c99 luastatic.lua.c liblua.a -rdynamic -lm -ldl -Ilua-5.2.4/src -o luastatic
```
I prefer to use `musl-gcc` which only supports static linking.  
Is it possible to make luasttic.lua provide option for static linking like the following?
```
cc -Os -std=c99 luastatic.lua.c liblua.a -static -lm -Ilua-5.2.4/src -o luastatic
```

**Comment by ers35** [comment]
luastatic supports both static and dynamic linking.

Here is a complete example:
```
#!/bin/sh

wget "https://www.lua.org/ftp/lua-5.2.4.tar.gz"
tar -xf lua-5.2.4.tar.gz
cd lua-5.2.4
make posix CC="musl-gcc -static"
echo "print(_VERSION)" > main.lua
CC=musl-gcc luastatic main.lua src/liblua.a -Isrc -static
```

**Comment by yuhangwang** [comment]
Thank you for the quick response. I tried your suggestion and the luastatic compilation command becomes this:
```
musl-gcc -Os -std=c99 main.lua.c ./liblua.a -rdynamic -lm -ldl -Ilua-5.2.4/src -static -o main
```
I guess `-static` will override the `-rdynamic` in this case and the output binary is a static one without any dependency.
Thanks!
