### ISSUE TITLE
Mimic error handling of standard Lua interpreter

### ISSUE THREAD

**Issue by mpeterv** [ers35/luastatic#8]
It would be nice if luastatic could mimic standard Lua interpreter behaviour when handling errors:

* Attempt to convert non-string error objects to string if they have `__tostring` metamethod, replace them with `(error objects is a %type% value)` otherwise.
* Append traceback to string errors.
* Print error message to stderr instead of stdout.

For reference see `handle_script` function in recent versions of `lua.c`.

**Comment by ers35** [comment]
Fixed in 1a62fc5.
