### ISSUE TITLE
Improve handling of syntax errors in a bundled modules

### ISSUE THREAD

**Issue by mpeterv** [ers35/luastatic#9]
Currently luastatic loader prints syntax error and completely exits if it fails to load a bundled module. It's more convenient to use standard loader interface and return some message including the syntax error from the loader to let `require` include it into its nicely formatted report and throw a normal Lua error.

Of course it's strange to bundle modules with syntax errors but there are some usecases, e.g. it's reasonable to have a module with Lua 5.3 bit operation syntax and attempt to load it with `pcall(require, "module_name")` and fallback to some other implementation if `require` fails.

**Comment by ers35** [comment]
Fixed in 1a62fc5.

**Comment by mpeterv** [comment]
Thanks for the prompt fixes!
